name: Smoke Tests (Scheduled)

on:
  workflow_dispatch:
  schedule:
    - cron: "15 03 * * *"

jobs:
  smoke:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Java 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "21"
          cache: maven

      - name: Run Smoke Tests
        run: mvn -B clean test -Psmoke

      - name: Generate Allure Report
        if: always()
        run: mvn -B allure:report
        
      - name: Upload Everything in Target
        if: always() # Hata olsa da olmasa da çalıştır
        uses: actions/upload-artifact@v4
        with:
          name: target-directory-backup
          path: target/ # Sadece screenshots değil, tüm target'ı bana getir  

      - name: Send Mail
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{ secrets.MAIL_USERNAME }}
          password: ${{ secrets.MAIL_PASSWORD }}
          subject: "BMS Test Raporu - ${{ github.run_number }}"
          to: senin_mail_adresin@gmail.com
          from: GitHub Actions
          body: Testler tamamlandı. Rapor ektedir.
          attachments: target/site/allure-maven-plugin/index.html
          
      
