name: Smoke Tests (Scheduled)

on:
  workflow_dispatch:
  schedule:
    - cron: "50 08 * * *"

jobs:
  smoke:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Java 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "21"
          cache: maven

      - name: Run Smoke Tests
        run: mvn -B clean test -Psmoke

      - name: Generate Allure Report
        if: always()
        run: mvn -B allure:report
        
      - name: Upload Everything in Target
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: target-directory-backup
          path: target/ 

      # Zipleme adımlarını sildik, yerine GitHub Pages adımını koyduk:
      - name: Deploy Allure Report to GitHub Pages
        if: always()
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: target/site/allure-maven-plugin

      - name: Send Mail
        uses: dawidd6/action-send-mail@v3
        if: always()
        with:
          server_address: ${{ secrets.SMTP_SERVER }}
          server_port: ${{ secrets.SMTP_PORT }}
          username: ${{ secrets.SMTP_USERNAME }}
          password: ${{ secrets.MAIL_PASSWORD }}
          subject: "QA Otomasyon Test Raporu"
          to: ${{ secrets.MAIL_TO }}
          from: ${{ secrets.MAIL_FROM }}
          secure: true
          body: |
            Merhaba, 
            Testler tamamlanmıştır. Raporu indirmeden, doğrudan tarayıcınızdan incelemek için aşağıdaki linke tıklayabilirsiniz:
            https://${{ github.repository_owner }}.github.io/bms-test-automation/
